# Generated by Django 2.2 on 2020-09-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='1.jpg', null=True, upload_to='')),
                ('header', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('pirce', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
